import Head from "next/head";
import Image from "next/legacy/image";
import { Top } from "../../components/eventlp/top";
import { NavBar } from "../../components/eventlp/nav";
import Link from "next/link";
import { client } from "../../libs/client";
import { Footer } from "../../components/footer";
import { Event } from "../../components/event";
import { Resolve } from "../../components/eventlp/resolve";
import { Whystop } from "../../components/eventlp/whystop";
import { Feature } from "@/components/eventlp/feature";
import { Message } from "@/components/eventlp/message";
import { Form } from "@/components/eventlp/form";
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blogs" });
  return {
    props: {
      blog: data.contents,
      totalCount: data.totalCount,
    },
  };
};

export default function Home({ blog, totalCount }) {
  const microCMSLoader = ({ src, width, quality }) => {
    return `${src}?auto=format&fit=max&w=${width}`;
  };
  // const eventNames = [];
  // {
  //   blog.map((d) => {
  //     if (d.category?.name === "event") {
  //       return eventNames.push(d);
  //     }
  //   });
  // }
  const eventNames = blog.filter((d) => d.category?.name === "event");

  // console.log(eventNames);
  return (
    <>
      <Head>
        <title>Restart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidde z-50 mb-10 bg-blue-200">
        <NavBar />
      </div>

      <div className="hidde">
        {" "}
        <Top newestBlog={blog[0]} />
      </div>
      <Resolve />
      <Whystop />
      <Feature />
      <Message />
      <div className="my-20">
        {" "}
        <Form />
      </div>

      {/* <Pagination totalCount={totalCount} /> */}
      <div className="mx-3 md:mx-20  my-40">
        <h2 className="m-5 p-5 text-center font-sans font-thin text-5xl">
          {/* Newest Article */}
        </h2>

        {/* <Event props={eventNames} /> */}
        {/* <Category /> */}
      </div>
      <Footer />
    </>
  );
}
