import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Top } from "../components/top";
import { NavBar } from "../components/nav";
import Link from "next/link";
import { client } from "../libs/client";
import { Nav } from "../components/header";
import { Footer } from "../components/footer";
import { Event } from "../components/event";
import { Pagination } from "@/components/Pagination";
import { Category } from "@/components/Category";
import Script from "next/script";
import { useState, useEffect } from "react";

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blogs" });
  return {
    props: {
      blog: data.contents,
      totalCount: data.totalCount,
    },
  };
};

export default function Home({ blog, totalCount }) {
  const microCMSLoader = ({ src, width, quality }) => {
    return `${src}?auto=format&fit=max&w=${width}`;
  };
  const eventNames = [];
  {
    blog.map((d) => {
      if (d.category?.name === "event") {
        return eventNames.push(d);
      }
    });
  }

  // console.log(eventNames);
  return (
    <>
      <Head>
        <title>GOGAKU English</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Top />
      <Pagination totalCount={totalCount} />

      <h2 className="m-10 p-10 text-center font-sans font-thin text-5xl">
        Newest Article
      </h2>

      <div className="md:grid grid-cols-3  gap-8 w-full text-center">
        {blog.slice(0, 3).map((d) => {
          const pathimage = d.eyecatch?.url;
          const datetime = new Date(d.createdAt);
          return (
            <div
              key={d.id}
              className="h-full  bg-slate-20 rounded-3xl px-5 border shadow-xl hover:shadow-2xl hover:scale-105 transition duration-500 ease-in-out"
            >
              <Link key={d.id} href={`/blog/${d.id}`}>
                <div className="bg-blue-20 rounded-xl">
                  <div className="text-left z-20 absolute">
                    <span className="border rounded-xl px-5 py-3  ml-2 bg-slate-800 font-serif font-light text-slate-100 ">
                      {d.category?.name}
                    </span>
                  </div>

                  {/* <Image
                    className="h-80 z-10"
                    loader={microCMSLoader}
                    src={pathimage}
                    height={500}
                    width={500}
                    alt="thumbnail"
                    priority
                  /> */}
                </div>

                <div className="py-20 px-8">
                  <h1 className="pb-3 text-xl font-semibold"> {d.title}</h1>
                  <h2 className="font-light text-left">
                    {d?.description?.substring(0, 85)}...
                    <span className="text-blue-200 pl-5">続きを読む</span>
                  </h2>

                  <div className="text-slate-700  py-8 opacity-50 border-t mt-10 flex justify-end ">
                    <p>更新日時 :</p>
                    <p>{datetime.getFullYear()}年</p>
                    <p>{datetime.getMonth() + 1}月</p>
                    <p>{datetime.getDate()}日</p>
                    <p>{datetime.getHours()}時</p>
                    <p>{datetime.getMinutes()}分</p>
                  </div>
                </div>
              </Link>
            </div>
          );
        })}
      </div>
      <Event props={eventNames} />
      <Category />
      <Footer />
    </>
  );
}
